name: CI
on: 
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade ivpm
        python -m ivpm update
    - name: Update
      run: |
        ivpm update
        make update
    - name: Commit changes
      run: |
        git status
        changes=`git status | egrep -e 'modified|deleted' | wc -l`
        if test $changes -ne 0; then
            echo "Changes"
        else
            echo "No changes"
        fi

